name: Build, Test and Push Images

on:
    workflow_dispatch:
    pull_request:  # Trigger on any pull request
        paths: # Trigger only when files in these paths change
            - '.github/workflows/build_image.yml'
            - 'ubuntu-images/ubuntu22_dockerfile'
    push:
        branches:
            - main  # Trigger on pushes to the main branch
        paths: # Trigger only when files in these paths change
            - '.github/workflows/build_image.yml'
            - 'ubuntu-images/ubuntu22_dockerfile'

jobs:
    build: 
        name: build image
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ubuntu-images/ubuntu22_dockerfile
                failure-threshold: warning
                override-info: DL3008

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ubuntu-images/ubuntu22_dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/base_images:ubuntu:22

    

