name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ubuntu: 'ubuntu-images/**'
            centos: 'centos-images/**'


  build:
    needs: changes
    if: ${{ needs.changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ${{ fromJson(needs.changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.component }}
        run: echo "Building ${{ matrix.component }}"