name: Test Docker Metadata Action

on:
    workflow_dispatch:
        inputs:
            version:
                description: "release version"
                required: false
    
jobs:
    build: 
        name: build image
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ secrets.DOCKERHUB_USERNAME }}/base_images
                tags: |
                  type=raw, value=ubuntu22
                  type=semver,pattern={{version}},value=${{ github.event.inputs.version }},enable=${{ github.event.inputs.version != '' }}


            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ubuntu-images/ubuntu22_dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}

