name: Test matrix generation based on the dockerfiles

on:
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      is_main: ${{ steps.check_main.outputs.is_main }}
    steps:
      - name: Check if branch is main
        id: check_main
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "is_main=true" >> $GITHUB_OUTPUT
          else
            echo "is_main=false" >> $GITHUB_OUTPUT
          fi

  generate-matrix:
    needs: check-branch
    if: needs.check-branch.outputs.is_main == 'true'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate matrix
        id: set-matrix
        run: |
          MATRIX=$(find . -name "*-dockerfile" | while read DOCKERFILE; do
            if [[ $DOCKERFILE == *"base-images"* ]] || [[ $DOCKERFILE == *"ci-images"* ]]; then
              IMAGE_TYPE=$(echo $DOCKERFILE | cut -d'/' -f2 | sed 's/-images//')
              OS_TYPE=$(echo $DOCKERFILE | cut -d'/' -f3)
              FILENAME=$(basename $DOCKERFILE)
              OS_VERSION=$(echo $FILENAME | grep -o '[0-9]\+')
              REGISTRY_PATH="${IMAGE_TYPE}/${OS_TYPE}/${OS_VERSION}"
              
              jq -n \
                --arg image_type "$IMAGE_TYPE" \
                --arg os_type "$OS_TYPE" \
                --arg os_version "$OS_VERSION" \
                --arg registry_path "$REGISTRY_PATH" \
                --arg dockerfile "$DOCKERFILE" \
                '{image_type: $image_type, os_type: $os_type, os_version: $os_version, registry_path: $registry_path, dockerfile: $dockerfile}'
            fi
          done | jq -s '{ "include": . }')

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "matrix=$MATRIX" 